import { expect, it } from 'vitest';
import { asksForImage } from '../src/main/session/image-request.js';

/**
 * Messy, everyday phrasings written separately from the rules: typos, slang, emoji, mixed
 * languages, long messages with the request in the middle, and developer look-alikes.
 */
const yes = [
  'pls generate a pic of a cat in a spacesuit lol',
  'yo can u make me a cool logo for my youtube channel 🔥',
  'hey! I am working on a birthday card for my mom. Could you create an image of a cake with candles?',
  'Thanks for the summary. Now please draw a cartoon version of our team mascot, a penguin.',
  'need a banner 1500x500 for twitter, dark blue, minimal',
  'create a image of a dog surfing',
  'Generate an photo realistic image of tokyo at night',
  'Make a meme with a cat saying "it works on my machine"',
  'Could you design a book cover illustration for a sci-fi novel?',
  'i\'d like a watercolor painting of venice',
  'Erstell mal ein Bild von einem Wal im All',
  'kannst du ein logo für meinen podcast machen?',
  'Hazme una imagen de un gato con sombrero, porfa',
  'Fais-moi une illustration d\'un renard qui lit',
  'Gera uma imagem de um astronauta surfando',
  'Сделай картинку с котом в шляпе',
  'Bana bir kedi görseli oluşturur musun?',
  'Tạo giúp mình một hình ảnh con mèo',
  '给我画一张猫的图片',
  '可爱的猫的插画を生成して',
  '귀여운 고양이 이미지 하나 만들어 줄래?',
  'Create a picture of a lighthouse, then save it as /workspace/lighthouse.png',
  'Create an image of a futuristic user interface on a glass wall',
  'Draw the lunar module landing on the moon',
  'Make a photo-style image of an old library with ISO 100 film grain',
  'Could you whip up a quick sketch of a bicycle?',
  'I would love an illustration for my blog post about gardening',
  'Produce a 4K wallpaper of a neon city in the rain',
  'Visualize a cozy reading nook as a photo',
  'Erzeuge ein Foto eines alten Leuchtturms bei Sturm',
  'Bitte zeichne mir eine Katze, die Gitarre spielt',
  'Genera una ilustración de un bosque encantado',
  'Me gustaría un póster minimalista de una montaña',
  'Crée-moi un logo pour ma boulangerie',
  'Je voudrais une image d\'un phare au coucher du soleil',
  'Desenhe um mapa de tesouro estilo pirata',
  'Gostaria de um papel de parede com o espaço sideral',
  'Нарисуйте, пожалуйста, замок на холме',
  'Мне нужна картинка для поста про весну',
  'Uzay temalı bir duvar kağıdı tasarla',
  'Bir ejderha resmi çizer misin?',
  'Vẽ giúp tôi một bức tranh phong cảnh núi',
  'Hãy tạo một áp phích cho buổi hòa nhạc',
  '请生成一张星空的壁纸',
  '幫我設計一個貓咪頭像',
  '星空の壁紙を作成してください',
  '우주 배경화면 만들어 주세요'
];
const no = [
  'the image in the README is broken, can you fix it?',
  'Generate a test image fixture in tests/fixtures for the upload test',
  'Why does the logo look blurry on retina screens?',
  'Add an og:image meta tag to index.html',
  'Write a bash command to batch-convert images to webp',
  'Draw conclusions from the survey results',
  'Make the images in the gallery lazy-load',
  'Optimize the images in public/ for the web',
  'Create an Image struct in Rust with width and height',
  'Generate a favicon.ico from the existing logo.svg with ImageMagick',
  'Find all photos larger than 5 MB in my Downloads folder',
  'Can you tell me what this picture shows?',
  'Draw the rest of the owl — just kidding, explain the algorithm instead',
  'Please create a Dockerfile for this image processing service',
  'Generiere ein Python-Skript, das Bilder zuschneidet',
  'Erstelle eine Funktion, die ein Bild zurückgibt',
  'Crea un script que convierta imágenes a PNG',
  'Écris un composant React qui affiche une image',
  'Напиши функцию, которая возвращает картинку',
  '写一个上传图片的组件',
  '画像をアップロードするコードを書いて',
  '사진을 압축하는 스크립트 만들어줘',
  'Make a docker image for the backend',
  'Build a container image and push it to the registry',
  'Can you check why the hero image is cropped on mobile?',
  'Please refactor the image upload handler',
  'Write unit tests for the thumbnail generator',
  'Add alt text to every image on the landing page',
  'Generate a sitemap that includes all image URLs',
  'Make the logo 20% smaller in the CSS',
  'Erstelle eine Liste aller Bilder ohne Alt-Text',
  'Optimiere die Bilder im Ordner public',
  'Crea una tabla con los tamaños de las imágenes',
  'Supprime les images inutilisées du projet',
  'Crie um script para baixar as fotos',
  'Удали все картинки из папки assets',
  'Resimleri webp formatına dönüştür',
  'Xóa tất cả hình ảnh trong thư mục cũ',
  '把图片转换成webp格式',
  '画像のサイズを小さくして',
  '로고 파일을 svg로 변환해줘',
  'How do I draw a circle on a canvas in JavaScript?',
  'Make a GIF of the terminal session',
  'Create a new branch called image-fixes'
];

it.each(yes)('counts %s', text => expect(asksForImage(text)).toBe(true));
it.each(no)('leaves %s with the mention', text => expect(asksForImage(text)).toBe(false));
